/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CubeType = IDL.Text;
export const TutorialStep = IDL.Record({
  'title' : IDL.Text,
  'algorithm' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCubeType' : IDL.Func([CubeType], [], []),
  'addTutorialStep' : IDL.Func([CubeType, TutorialStep], [], []),
  'getAllCubeTypes' : IDL.Func([], [IDL.Vec(CubeType)], ['query']),
  'getCubeType' : IDL.Func([CubeType], [IDL.Vec(TutorialStep)], []),
  'getTutorialStep' : IDL.Func([CubeType, IDL.Nat], [TutorialStep], []),
  'removeCubeType' : IDL.Func([CubeType], [], []),
  'removeTutorialStep' : IDL.Func([CubeType, IDL.Nat], [], []),
  'searchByAlgorithm' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(CubeType, TutorialStep))],
      ['query'],
    ),
  'swapTutorialSteps' : IDL.Func([CubeType, IDL.Nat, IDL.Nat], [], []),
  'updateTutorialStep' : IDL.Func([CubeType, IDL.Nat, TutorialStep], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CubeType = IDL.Text;
  const TutorialStep = IDL.Record({
    'title' : IDL.Text,
    'algorithm' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'addCubeType' : IDL.Func([CubeType], [], []),
    'addTutorialStep' : IDL.Func([CubeType, TutorialStep], [], []),
    'getAllCubeTypes' : IDL.Func([], [IDL.Vec(CubeType)], ['query']),
    'getCubeType' : IDL.Func([CubeType], [IDL.Vec(TutorialStep)], []),
    'getTutorialStep' : IDL.Func([CubeType, IDL.Nat], [TutorialStep], []),
    'removeCubeType' : IDL.Func([CubeType], [], []),
    'removeTutorialStep' : IDL.Func([CubeType, IDL.Nat], [], []),
    'searchByAlgorithm' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(CubeType, TutorialStep))],
        ['query'],
      ),
    'swapTutorialSteps' : IDL.Func([CubeType, IDL.Nat, IDL.Nat], [], []),
    'updateTutorialStep' : IDL.Func([CubeType, IDL.Nat, TutorialStep], [], []),
  });
};

export const init = ({ IDL }) => { return []; };